test(SCOUT): [BLA-1014] Test failure should fail the pipeline

diff --git a/.github/workflows/validations.yml b/.github/workflows/validations.yml
--- a/.github/workflows/validations.yml
+++ b/.github/workflows/validations.yml
@@ -76,6 +76,11 @@ jobs:
         run: npm run lint
 
       - name: Test
-        run: npm test
+        run: |
+          npm test
+          if [ $? -ne 0 ]; then
+            echo "Tests failed. Exiting..."
+            exit 1
+          fi
         env:
           CI: true
